import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Footer } from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const navLinks = [
  { id: 1, url: "#home", newTab: false, text: "Home" },
  { id: 2, url: "#features", newTab: false, text: "Features" },
  { id: 3, url: "#pricing", newTab: false, text: "Pricing" },
  { id: 4, url: "#contact", newTab: false, text: "Contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar
          links={navLinks}
          logoUrl={""}
          logoText={"AR-TechLab"}
        />
        <main className="bg-black text-gray-100 min-h-screen">
          {children}
        </main>
        <Footer
        />
      </body>
    </html>
  );
}
